export const OVERPAYING_THRESHOLD_RATIO = 1.3;

export const VENDOR_SPENDING_SPIKE_RATIO = 1.5;
export const MIN_VENDOR_HISTORY_FOR_SPIKE_CHECK = 3;

export const LARGE_PURCHASE_RATIO = 3;
export const MIN_TRANSACTIONS_FOR_BASELINE = 5;
