import { TBankCompany } from './bank-company.constant';

export const BANK_CREDENTIAL_FIELDS = {
  ID: 'id',
  NUM: 'num',
  EMAIL: 'email',
  USER_CODE: 'userCode',
  USERNAME: 'username',
  PASSWORD: 'password',
  NATIONAL_ID: 'nationalID',
  PHONE_NUMBER: 'phoneNumber',
  CARD_6_DIGITS: 'card6Digits',
} as const;

export type BankCredentialFieldType =
  (typeof BANK_CREDENTIAL_FIELDS)[keyof typeof BANK_CREDENTIAL_FIELDS];

const USERNAME_LOGIN = [
  BANK_CREDENTIAL_FIELDS.USERNAME,
  BANK_CREDENTIAL_FIELDS.PASSWORD,
];

const ID_LOGIN = [BANK_CREDENTIAL_FIELDS.ID, BANK_CREDENTIAL_FIELDS.PASSWORD];

const DISCOUNT_GROUP_LOGIN = [
  BANK_CREDENTIAL_FIELDS.ID,
  BANK_CREDENTIAL_FIELDS.PASSWORD,
  BANK_CREDENTIAL_FIELDS.NUM,
];

const ISRACARD_GROUP_LOGIN = [
  BANK_CREDENTIAL_FIELDS.ID,
  BANK_CREDENTIAL_FIELDS.CARD_6_DIGITS,
  BANK_CREDENTIAL_FIELDS.PASSWORD,
];

// Mirrors the login fields israeli-bank-scrapers requires per company.
export const REQUIRED_CREDENTIAL_FIELDS_BY_COMPANY: Record<
  TBankCompany,
  BankCredentialFieldType[]
> = {
  [TBankCompany.MAX]: USERNAME_LOGIN,
  [TBankCompany.LEUMI]: USERNAME_LOGIN,
  [TBankCompany.UNION]: USERNAME_LOGIN,
  [TBankCompany.MASSAD]: USERNAME_LOGIN,
  [TBankCompany.PAGI]: USERNAME_LOGIN,
  [TBankCompany.MIZRAHI]: USERNAME_LOGIN,
  [TBankCompany.VISA_CAL]: USERNAME_LOGIN,
  [TBankCompany.BEINLEUMI]: USERNAME_LOGIN,
  [TBankCompany.OTSAR_HAHAYAL]: USERNAME_LOGIN,
  [TBankCompany.BEHATSDAA]: ID_LOGIN,
  [TBankCompany.BEYAHAD_BISHVILHA]: ID_LOGIN,
  [TBankCompany.DISCOUNT]: DISCOUNT_GROUP_LOGIN,
  [TBankCompany.MERCANTILE]: DISCOUNT_GROUP_LOGIN,
  [TBankCompany.AMEX]: ISRACARD_GROUP_LOGIN,
  [TBankCompany.ISRACARD]: ISRACARD_GROUP_LOGIN,
  [TBankCompany.HAPOALIM]: [
    BANK_CREDENTIAL_FIELDS.USER_CODE,
    BANK_CREDENTIAL_FIELDS.PASSWORD,
  ],
  [TBankCompany.ONE_ZERO]: [
    BANK_CREDENTIAL_FIELDS.EMAIL,
    BANK_CREDENTIAL_FIELDS.PASSWORD,
    BANK_CREDENTIAL_FIELDS.PHONE_NUMBER,
  ],
  [TBankCompany.YAHAV]: [
    BANK_CREDENTIAL_FIELDS.USERNAME,
    BANK_CREDENTIAL_FIELDS.NATIONAL_ID,
    BANK_CREDENTIAL_FIELDS.PASSWORD,
  ],
};
